# Simple workflow for deploying a Vite/React/TypeScript project to GitHub Pages
name: Deploy Vite Project to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read # Allow reading of the repository contents
  pages: write   # Allow writing to GitHub Pages
  id-token: write # Required for OpenID Connect (OIDC) authentication

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job to create the production ready files
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or '18', or specific version if needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # This command creates your 'dist' folder

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'dist' directory as the artifact
          path: './dist' # <--- IMPORTANT: This targets your built output

  # Deploy job to deploy the artifact to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4